#!/bin/bash


if [ $# -lt 1 ]
then
  echo "Usage: $0 {text} {options}"
  exit 1
fi

TEXT=$1
shift

convert -fill white -background 'srgb(10,10,10)' -font "${BRAILLE_FONT}" -pointsize 400 label:"${TEXT}" /tmp/img.png
convert /tmp/img.png -fuzz 10% -trim +repage /tmp/output.png
brailler /tmp/output.png $*
