[package]
name = "brailler"
version = "0.2.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
ffmpeg-next = "7.1.0"
image = "0.25.5"
imageproc = "0.25.0"
infer = "0.19.0"
